# Generated by Django 4.1.1 on 2024-09-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_product_type_product_allergens_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
