# Generated by Django 4.1.1 on 2024-09-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_allergen_alter_product_allergens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='number',
            new_name='allergen_number',
        ),
    ]
