# Generated by Django 4.1.1 on 2024-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_rename_number_allergen_allergen_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(to='viewer.allergen'),
        ),
    ]
